name: PHPDrafter tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-versions }}
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl,json,mbstring,uopz
          coverage: pcov
          tools: pecl,phpstan,phpunit,cs2pr,phpcs

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: PHPStan
        run: phpstan analyse --level=4 --error-format=checkstyle src/ | cs2pr

      - name: PHPCS
        run: phpcs --standard=tests/phpcs.xml --ignore=\*Minifier.php src/ | cs2pr

      - name: Upload coverage result
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage.xml

      - name: Render HTML
        run: php ./phpdraft -f tests/statics/full_test.apib > build/out/output.html

      - name: Test Files
        uses: Cyb3r-Jak3/html5validator-action@v0.4
        with:
          root: build/out/
          css: true

      - name: Link Checker
        uses: peter-evans/link-checker@v1

  analytics:
    name: Analytics
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download coverage
        uses: actions/download-artifact@v1
        with:
          name: coverage

      - name: Code coverage Scan
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}